spring:
  datasource:
    url: jdbc:postgresql://localhost:5312/Diploma
    username: postgres
    password: 15968

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /docs

app:
  baseApi: /antiprocrastinate-api
  apiVer1: /v1
  endpoints:
    categories: /categories
    groups: /groups
    priorities: /priorities
    statuses: /statuses
    tasks: /tasks
    users: /users